build.cake
Not quite ready to call this beta, let's keep it as -alpha* for now.
=> Changing to alpha versions for nugets

build.sh
Bootstrapper had the workaround added twice.  This cleans it up.
=> Cleaned up duplicate work around

maps/source/Additions/Additions.cs
* 10.2.4
Yes.
Xamarin.GooglePlayServices.Maps
Before: ``Polygon.SetHoles(IList<LatLng> holes)``
After: ``Polygon.SetHoles(IList<IList<LatLng>> holes)``
I think ``Polygon.SetHoles(IList<LatLng> holes)`` is wrong parameter type.
Because the original Google Maps Android API has ``List<List<LatLng>>`` parameter type.
[``Polygon::setHoles (List<? extends List<LatLng>> holes)``](http://bit.ly/2rlfJPO)
I fix this and works fine in my test apps.
=> [maps]Fix wrong Polygon.SetHoles parameter type

protolite-well-known-types/nuget/Xamarin.Firebase.ProtoliteWellKnownTypes.template.nuspec, protolite-well-known-types/source/Properties/AssemblyInfo.cs
15.0.1
No
Firebase.Firestore requires `Xamarin.Firebase.ProtoliteWellKnownTypes`, but `Xamarin.Firebase.ProtoliteWellKnownTypes` 's nuget id is `Xamarin.GooglePlayServices.ProtoliteWellKnownTypes`.
So I renamed.
=> Fix ProtoliteWellKnownTypes nuget package id

source/com.google.firebase/firebase-perf/Transforms/Metadata.xml
Add the proper Reference for the Trace class to be visible for the newtrace method
Version: 9.0
FirebasePerformance.Instance.NewTrace in firebase-perf
Right now the new AAR downloaded for firebase performance is the version 16.2.0 in the config.json file.
This native file has a new implementation for the method newtrace as follow :
`com.google.firebase.perf.internal.zzb` instead of `com.google.android.gms.internal.firebase-perf.zze` that was available in the previous version.
=> Fix for NewTrace method in FireBase Performance Monitoring

source/com.google.android.gms/play-services-basement/merge.targets
Latest
Nope
If used in a Xamarin.Android project with aapt2,
`@(GoogleServicesJson)` items cause targets to run on every build:
Building target "_ConvertLibraryResourcesCases" completely.
Input file "obj\Debug.stamp" does not exist.
So one problem, is Xamarin.Android has some logic to decide the path
of the `.stamp` file on directories that are normally in
`obj\Debug\lp\1\`:
https://github.com/xamarin/xamarin-android/blob/b6f7f0e40ac9e500acd59ba61f045f7dde5dcc99/src/Xamarin.Android.Build.Tasks/Tasks/CollectNonEmptyDirectories.cs#L30
We need to make fixes in Xamarin.Android, but a workaround is to set
the `%(StampFile)` metadata on `@(LibraryResourceDirectories)`. This
will make our targets rerun aapt2 only when a `@(GoogleServicesJson)`
file changes.
=> [msbuild] fix for $(AndroidUseAapt2)

source/com.google.android.gms/play-services-basement/buildtasks/Basement-BuildTasks.csproj
Latest?
No
In .NET 5+, builds fail with:
error MSB4062: The "Xamarin.GooglePlayServices.Tasks.ProcessGoogleServicesJson" task could not be loaded from the assembly
Xamarin.GooglePlayServices.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
We need to port this project from .NET 4.5 to `netstandard2.0` to fix
this issue.
I targeted the MSBuild 15.9.x NuGet packages in case VS 2017 is a
concern at all.
=> [build] port MSBuild tasks to netstandard2.0

template.targets
Since Xamarin.Build.Download 0.10.0, the `XamarinBuildDownloadRestoreAssemblyAar` item group is no longer necessary or used, however the existence of items in this group generate a build warning which is confusing many users.  
We kept both of these in this package in case old versions of XBD were used in a project, especially those which relied on an old Xamarin.Android that did not support the new `AndroidAarLibrary` item group which the new XBD `XamarinBuildDownloadAndroidAarLibrary` item leverages to avoid embedding the .aar inside the .dll at build time.
I think at this point it is safe to remove as we are many Xamarin.Android versions since the new support was added for including aar's from a file in the build, and we are a few GPS/FB releases that users could stick to which still …
=> Remove `XamarinBuildDownloadRestoreAssemblyAar`

config.json
https://github.com/xamarin/XamarinComponents/issues/956
1XX
No, only bump version
New artifacts in config.json Xamarin.Google.Android.DataTransport.TransportRuntime:2.2.3 and Xamarin.Google.Android.DataTransport.TransportBackendCct:2.2.3. Bump version of Xamarin.Firebase.Crashlytics and Xamarin.Firebase.Crashlytics.NDK to 117.1.0
Note:
Xamarin.Google.Android.DataTransport.TransportRuntime and Xamarin.Google.Android.DataTransport.TransportbackendCct 2.2.3 I summited a pull request https://github.com/xamarin/XamarinComponents/pull/1008
=> Xamarin.Firebase.Crashlytics bump version to 117.1.0

config.json, source/GooglePlayServicesSolutionFilter.cshtml
Binderator generates a `GooglePlayServices.sln` file which can be used in Visual Studio, however it contains 110 projects, which does not make VS very happy. This adds a template to generate solution filter (.slnf) files next to each project file. This allows you to open only the current project plus its project references in Visual Studio.
=> Generate solution filters for working in Visual Studio.

build.cake
Use `MSBuild`'s `/restore` command to do the NuGet restore while building the solution, instead of doing it as a separate step first.  This means we don't have to parse the solution file twice.
=> [build] Use fewer NuGet restores.

config.json, source/com.google.android.gms/play-services-ads/Transforms/Metadata.xml, source/com.google.firebase/firebase-firestore/Transforms/Metadata.xml, source/com.google.firebase/firebase-iid/Transforms/Metadata.xml, source/com.google.firebase/firebase-inappmessaging/Transforms/Metadata.xml, source/com.google.firebase/protolite-well-known-types/Transforms/Metadata.xml
- com.google.android.gms.play-services-ads (19.1.0 -> 19.3.0)
- [breaking.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5617553/Xamarin.GooglePlayServices.Ads.dll.breaking.txt)
- [diff.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5617554/Xamarin.GooglePlayServices.Ads.dll.diff.txt)
- com.google.android.gms.play-services-ads-base (19.1.0 -> 19.3.0)
- No public API changes
- com.google.android.gms.play-services-ads-lite (19.1.0 -> 19.3.0)
- [breaking.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5617567/Xamarin.GooglePlayServices.Ads.Lite.dll.breaking.txt)
- [diff.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5617569/Xamarin.GooglePlayServices.Ads.Lite.dll.diff.txt)
- …
=> GPS/FB July 2020 Updates

build/scripts/update-config.csx
The new weekly stable update script has logic to detect GPS components that need to have 100 added to the version number (ie: `18.0.0` -> `118.0.0`), however there is a bug where it was checking for an additional period after the version, which will only happen when the existing nuget version contains 4 parts (`18.0.0.0` instead of `18.0.0`).  This PR removes that requirement so it should always work correctly.
=> [update-config.csx] Fix issue causing incorrect nuget version numbers for GPS.

source/GooglePlayServicesProject.cshtml
* removing prefix "1" from nuget version to obtain artifact version in tags
current binderator API does not expose Android artifact version, so it must be calculated from NuGet version
* fixing "patch" part of the version
Previous version did not take into account possible prerelase suffix, so parsing did cut off patch part (instead of 120.0.0 it would be 120.0)
sample for both cases:
```
artifact=androidx.core:core artifact_versioned=androidx.core:core:1.5
```
https://www.nuget.org/packages/Xamarin.AndroidX.Core/
=> artifact version from nuget version in tags fixes and improvements

azure-pipelines.yaml, config.json
Currently our CI seems to be producing **different** builds between Windows & Mac:
16.9 - Windows:
16.9 - Mac:
This comparison works against the versions on NuGet.org, so I guess we publish the packages created on Mac to NuGet, which shows fewer differences.
Unrelated, we should update to the latest XA: 16.10.  Using this version, both Windows & Mac show the same diffs as Windows XA 16.9.  It would seem like the Mac XA 16.9 package was not as recent as the Windows one.
16.10 - Mac
Additionally, let's bump the patch version of the NuGets with diffs, so updated versions will get pushed to NuGet.org, reducing noise on future diffs.
=> [yaml] Update to XA 16.10.

azure-pipelines.yaml, build.cake, global.json, source/GooglePlayServicesProject.cshtml
Context: https://github.com/xamarin/GooglePlayServicesComponents/pull/418
The first step in multi-targeting GPS/FB/MLKit with `net6` is to migrate to `Xamarin.Legacy.Sdk`, which runs on top of .NET 6 but can build `MonoAndroid9.0`.  We'll commit this first to help make it easier to run our diff logic on the resulting packages to make sure there are no regressions.  A future commit will then enable `net6`.
Changes made:
- CI - Install .NET 6 Preview 5
- CI - Install the Android workload
- Change Cake to use `DotNetCore` versions
- Update `Sdk` to `Xamarin.Legacy.Sdk`
=> Convert to Xamarin.Legacy.Sdk.

Directory.Build.props, azure-pipelines.yaml
The release of .NET 6 P7 broke our use of `dotnet workload install microsoft-android-sdk-full` for P6, which is causing our CI setup to fail:
```
Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.100-preview.6.21355.2
Installing workload manifest microsoft.net.sdk.android version 30.0.100-preview.7.110.
Installing workload manifest microsoft.net.sdk.ios version 15.0.100-preview.7231.
Installing workload manifest microsoft.net.sdk.maccatalyst version 15.0.100-preview.7231.
Installing workload manifest microsoft.net.sdk.macos version 12.0.100-preview.7231.
Installing workload manifest microsoft.net.sdk.maui version 6.0.100-preview.7.1345.
Installing workload manifest microsoft.net.sdk.tvos version 15.0.100-preview.7231.
Installing workload manifest …
```
=> [build] Bump to .NET 6 - Preview 7.

azure-pipelines.yaml
Like https://github.com/xamarin/AndroidX/pull/197, we should only sign NuGets for tags (releases).  There is no reason to sign for PR builds, especially PR's from forks where signing will fail due to security checks.
=> [build] Only sign NuGets for tags (releases).

source/com.google.android.play/core/Transforms/Metadata.xml
Android Play Core 1.10.0
Yes
More details in issue #483
=> Change Play.Core binding transforms to fix inconsistency with native library

config.json
`Xamarin.Firebase.AppIndexing` is a circular dependency with AndroidX.  We need this package to be `net6.0-android` in order to build AndroidX.  Then we'll need it updated again to use `net6.0-android` versions of AndroidX.
=> Release Xamarin.Firebase.AppIndexing with net6.0-android for AndroidX dependency.

azure-pipelines.yaml, workload.json
Copied from: https://github.com/xamarin/AndroidX/pull/413
Context: https://github.com/xamarin/xamarin-android/commits/release/6.0.1xx-preview10
Context: https://github.com/dotnet/maui/wiki/Installing-.NET-6
We need to build with a version of the .NET 6 `android` workload that
contains the fix:
https://github.com/xamarin/java.interop/commit/2d5431f765928e5377288d3284ace3c5d871755a
For .NET 6, we should:
1. Install the latest public .NET 6 RC 2 release.
2. Use a `workload.json` file to pin to a specific build of the
`android` workload.
3. Use the `dotnet6` feed when installing the workload.
I used the `workload.json` file currently reported by running:
dotnet workload update --print-rollback
I adjusted the version number to match the appropriate build of:
"microsoft.net.sdk.android": …
=> Bump to xamarin/xamarin-android/release/6.0.1xx-preview10@27295e27

config.json, source/com.google.android.gms/play-services-auth-base/Transforms/Metadata.xml
Fixes #532.
In `play-services-auth-base-17.1.3` the base class for `com.google.android.gms.auth.GoogleAuthUtil` was changed:
17.1.2:
```java
public final class GoogleAuthUtil extends zzg { ... }
```
17.1.3:
```java
public final class GoogleAuthUtil extends zzl { ... }
```
We do not normally bind `zzl` because it is an obfuscated type, however if we don't the `GoogleAuthUtil` class does not get bound since the base type is missing.
Add metadata to bind `zzl`, which results in `GoogleAuthUtil` being bound.
=> [play-services-auth-base] Mark needed type as not obfuscated.

azure-pipelines.yaml, templates/codehaus-mojo/cgmanifest.json
Context: https://eng.ms/docs/initiatives/executive-order/executive-order-requirements/executiveorderoncybersecurity/softwarebillofmaterials
Context: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/secure-supply-chain/ado-sbom-generator
Context: https://github.com/xamarin/yaml-templates/blob/3a4be9e8fa257a139cec3014eb89a0fd5cd60b56/compliance/sbom/job.v1.yml
Context: https://devdiv.visualstudio.com/DevDiv/_componentGovernance/114855/alert/6201443
A new job has been added to generate a Software Bill of Materials using
shared yaml templates.
The com.google.code.gson dependency has also been updated to 2.8.9.
=> [ci] Generate a Software Bill of Materials

azure-pipelines.yaml
AndroidX/GooglePlayServices switched to using a private agent pool in order to meet the EO requirements. This pool is elastic, however agents can be reused if they become available while a job is waiting in the queue.
This means that the image may not always be fresh, and the image may contain a newer Xamarin.Android vsix than the one we want to use.  Unfortunately `vsixinstaller.exe` cannot downgrade an installed package, which causes us to build with the newer one instead of our intended one.
A new command was added to `boots` (`--downgrade-first`) which will first revert the installed Xamarin.Android vsix to the one that shipped with the target version of Visual Studio.
Update to the latest preview of `boots`, and call the new command.
Also switches to `dotnet tool update` which can …
=> [ci] Update boots to fix vsix downgrade issue

config.json, samples/Directory.Build.targets, source/com.github.bumptech.glide/annotations/Xamarin.Android.Glide.Annotations.targets, source/com.github.bumptech.glide/disklrucache/Xamarin.Android.Glide.DiskLruCache.targets, templates/glide/Project.cshtml
During migration of template set from XamarinComponents `*.targets` files were copied into wrong destination folders (and renamed).
=> fix for template set glide - artifact not found in nuget (issue 545)

azure-pipelines.yaml, workloads.json
Update:
- .NET 6 to `6.0.400`
- `microsoft.net.sdk.android` workload to `32.0.448`
- Classic to VS `17.3` versions (XA `13.0`)
Remove extraneous `UseDotNet` task now that we no longer use both `3.1` and `6.0`.  The base template will install `$(DotNetVersion)` for us.
- No API changes, as expected
- `<AndroidLibrary>` packages now include `.aar`:
=> Update dotnet to `6.0.400` and classic to `17.3`.

cgmanifest.json, config.json, docs/artifact-list-with-versions.md, samples/Directory.Build.targets
Could be.
Updated packages:
- `com.google.mlkit:vision-common` - 17.2.0 -> 17.2.1
=> Manual updates 20221004 MLKit only

Directory.Build.props
The bugs in the new JavaTypeSystem that were preventing us from using it have been fixed.
A side benefit of using it is speed:
|  | Legacy ApiXmlAdjuster | JavaTypeSystem |
| -- | -- | -- |
| Mac Build | 71:56 min | 40:21 min |
| Windows Build | 19:49 min | 13:31 min |
(Our Windows build agents are much more powerful machines than our Mac build agents.)
=> [Directory.Build.props] Use JavaTypeSystem.

azure-pipelines.yaml
In order to meet DevDiv "secure supply chain" requirements for CI machines that build software that is shipped, we need to use some special VM images that have been "locked-down" further than the publicly available Azure Pipelines images.
Our Windows `android-win-2022` image already meets this requirement.
This PR updates the Mac image to `internal-macos12` to meet this requirement.
As a side-effect, it looks like this image is twice as fast??!??
Mac Build: `160 min` -> `87 min` 🎉🥳🎈
=> Use internal locked-down Mac VM image for building.

azure-pipelines.yaml, global.json
Port the following infrastructure PR's from AndroidX to GPS:
- https://github.com/xamarin/AndroidX/pull/644
- https://github.com/xamarin/AndroidX/pull/645
- https://github.com/xamarin/AndroidX/pull/647
=> [ci] Fail build if .NET android/maui workloads cannot be installed.

azure-pipelines.yaml
Port https://github.com/xamarin/AndroidX/pull/393 to GPS.
Fixes CI error:
```
TSA was given an invalid Area Path: 'DevDiv\Xamarin SDK\Android'.
```
=> [ci] Update TSA area path since old one no longer exists.

SignList.xml, config.json, published-namespaces.txt, source/com.android.billingclient/billing-ktx/Transforms/EnumFields.xml, source/com.android.billingclient/billing-ktx/Transforms/EnumMethods.xml, source/com.android.billingclient/billing-ktx/Transforms/Metadata.xml, source/com.android.billingclient/billing/Additions/Additions.cs, source/com.android.billingclient/billing/Transforms/EnumFields.xml, source/com.android.billingclient/billing/Transforms/EnumMethods.xml, source/com.android.billingclient/billing/Transforms/Metadata.xml
Import Xamarin.Android.Google.BillingClient* packages from XamarinComponents so they will be supported.
Note this now uses the GooglePlayServices template, which is correct, as this package is licensed under the Android SDK License, it is not Apache, and thus we should not be including the `.aar` in the NuGet like we previously were.
Note also that we are _still_ including the `.aar` in the NuGet, which is incorrect, however this is a bug in our GPS template which is currently doing this for all packages and needs to be fixed separately.
Same notes apply for this package.
=> Import `Xamarin.Android.Google.BillingClient*` packages from XamarinComponents.

cgmanifest.json, config.json, docs/artifact-list-with-versions.md, samples/Directory.Build.targets
- `com.google.dagger:dagger` - 2.41 -> 2.42
- `com.google.errorprone:error_prone_annotations` - 2.14.0 -> 2.15.0
- `com.google.zxing:core` - 3.5.0 -> 3.5.1
- `com.google.flatbuffers:flatbuffers-java` - 1.12.0 -> 2.0.8
- `com.google.protobuf:protobuf-javalite` - 3.21.9 -> 3.21.12
=> Manual updates 20221216 dependencies cleanup

azure-pipelines.yaml, build.cake, nuget-diff.cake, validation.cake
Switch to using the streamlined CI pipeline in the AndroidX repository instead of the previous one in XamarinComponents.
AndroidX pipeline: https://github.com/xamarin/AndroidX/pull/658
=> Use new CI pipeline in AndroidX instead of XamarinComponents.

.github/workflows/new-releases-check.yml, build/scripts/update-config.csx
Fix 2 issues that are preventing our periodic stable update checks from running:
```
A compatible installed .NET Core SDK for global.json version [6.0.403] from [/home/runner/work/GooglePlayServicesComponents/GooglePlayServicesComponents/global.json] was not found
3.1.426 [/home/runner/.dotnet/sdk]
Install the [6.0.403] .NET Core SDK or update [/home/runner/work/GooglePlayServicesComponents/GooglePlayServicesComponents/global.json] with an installed .NET Core SDK:
```
^^ Fix by installing .NET 6 instead of .NET Core 3.
```
System.ArgumentException: '22.12.06' is not a valid version string. (Parameter 'value')
at NuGet.Versioning.SemanticVersion.Parse(String value)
at Submission#0.GetVersion(String s) in C:\g\build\scripts\update-config.csx:line 214
at …
```
=> [update-config.csx] Fix stable updates action.

azure-pipelines.yaml
Recent builds have been timing out during Component Governance:
[ERROR] The execution did not complete in the alotted time (360 seconds) and has been terminated prior to completion
[ERROR] To override the default timeout, use the pipeline variable ComponentDetection.Timeout with a larger integer value (in seconds).
Additionally, CodeQL increases the build time when it runs successfully.
Timeout values have been increased to account for these issues.
=> [ci] Increase build and CG timeout values

.github/workflows/new-releases-check.yml
No.
GitHub actions fail to run, because of outdated actions using Node v12. New updated actions use Node v16.
```
[build](https://github.com/xamarin/AndroidX/actions/runs/4635871484/jobs/8203265833#step:6:105)
GitHub Actions is not permitted to create or approve pull requests.
[build](https://github.com/xamarin/AndroidX/actions/runs/4635871484/jobs/8203265833)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-dotnet@v1, peter-evans/create-pull-request@v3. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> github actions updates

global.json, utilities.cake
Context: https://github.com/xamarin/AndroidX/pull/722
For some reason, `0.2.0-alpha4` of `Xamarin.Legacy.Sdk` causes package dependencies to be placed in the `/bin` directory whereas previously they were not.  Our published namespace script looks for all `.dll`'s in the `/generated` directory, which previously did not include dependencies.  This resulted in adding namespaces that were in dependencies and not just the assemblies packaged in this repository.
To fix this, we can restrict ourselves to looking for assemblies in the `/obj` directory, which does not contain dependency assemblies.
=> [utilities.cake] Only look for namespaces in "obj" assemblies.

source/GooglePlayServicesTargets.cshtml
Context: https://github.com/xamarin/AndroidX/pull/729
Context: https://github.com/xamarin/xamarin-android/pull/8025
A customer reported a build error such as:
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.46\targets\Microsoft.Android.Sdk.AndroidLibraries.targets(77,5):
error XACAAR7014: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
at System.Text.StringBuilder.ToString()
at Xamarin.Android.Tasks.CreateAar.RunTask()
at Microsoft.Android.Build.Tasks.AndroidTask.Execute()
Somewhere here:
https://github.com/xamarin/xamarin-android/blob/c31f3eda63a16e412a39fa61eb0f885be3c5f543/src/Xamarin.Android.Build.Tasks/Tasks/CreateAar.cs#L108-L114
We have a compounding issue:
* Google Play Services NuGets add `proguard.txt` files to class …
=> [msbuild] only include `@(ProguardConfiguration)` in apps

Directory.Build.props, source/GooglePlayServicesProject.cshtml
Some GPS interfaces provide useful API as `default` interface methods.  Support for default interface methods has been added to C# and our Android binding tools.
Enable `$(AndroidBoundInterfacesContainStaticAndDefaultInterfaceMethods)` so that this support is turned on.
Note there are a few packages that have build errors with this enabled.  Those packages will continue to have this setting turned off.  The issue has been filed here: https://github.com/xamarin/java.interop/issues/1116.
=> Enable DIM for GPS packages

config.json
No.
Attempt to fix CG errors like it was solved in AX repo.
Context:
There are 2 jobs related to CG
"Run component detection"
and 
"Component Detection (auto-injected by policy)"
Link to untagged (not for publishing) builds (2nd CG job was not run):
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8575806&view=logs&j=3b059b26-55fe-5273-567a-5b3fa6c051e7&t=c1153fc3-0ba8-5af1-b921-60affc994bb3
Tagged builds skip CG step #1, but run #2
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8575864&view=logs&j=3b059b26-55fe-5273-567a-5b3fa6c051e7&t=c1153fc3-0ba8-5af1-b921-60affc994bb3
Now POM errors in tagged builds (for publishing)
New error fails when CI runs CG step and analyzes pom.xml file in ./generated/*/pom.xml
We have been generating pom.xml for eons with 
1. …
=> FIX for CG errors - pom.xml renamed to dependencies.pom

azure-pipelines.yaml
=> Manual updates 20231215 - CI timeouts 300 minutes

Directory.Build.props, build.cake, source/GooglePlayServicesProject.cshtml, source/com.google.mlkit/object-detection-custom/Transforms/Metadata.net7.0-android.xml, source/com.google.mlkit/object-detection/Transforms/Metadata.net7.0-android.xml, source/com.google.mlkit/pose-detection-accurate/Transforms/Metadata.net7.0-android.xml, source/com.google.mlkit/pose-detection/Transforms/Metadata.net7.0-android.xml
Context: https://github.com/xamarin/AndroidX/pull/820
Like https://github.com/xamarin/AndroidX/pull/820 for AndroidX, use an updated `generator` that surfaces API Google has marked with `@RestrictTo` with a warning for consumers that the API is not considered public.
Sample from `api-diff`:
Obsoleted methods:
```diff
[Obsolete ("While this member is 'public', Google considers it internal API and reserves the right to modify or delete it in the future. Use at your own risk.")]
public virtual void SetBlockingExecutor (Java.Util.Concurrent.IExecutorService executor);
[Obsolete ("While this member is 'public', Google considers it internal API and reserves the right to modify or delete it in the future. Use at your own risk.")]
public virtual void SetNonBlockingExecutor …
```
=> Use an updated `generator` for `@RestrictTo` support.

azure-pipelines.yaml
As part of Microsoft's continued push for supply chain security, our CI that builds shipping software must extend an "official" template that can be used to ensure various safety checks have run.
Unfortunately, this requires extensive changes to our CI to fit their model.  This PR requires both necessary changes and cleanup done to make our process mesh better with the template.
The only functional difference should be:
- Previously the outputs of both the `Windows` and `MacOS` builds were copied to the same artifact directory (`"nuget"`) which was signed and released.  This meant that the last one written "won" and that's what we shipped.  The new template didn't like multiple agents writing to the same output directory, so now we only write to `output-windows` and `output-macos`, and we …
=> [ci] Switch to using the 1ES mandated pipeline template.

cgmanifest.json, config.json, docs/artifact-list-with-versions.md, samples/Directory.Build.targets
No. Freezing packages because of size limit no NuGet gallery.
Froze packeges.
=> Manual updates 20240315 freeze tf ops

Directory.Build.props, README.md, azure-pipelines.yaml, build.cake, published-namespaces.txt, samples/Directory.Build.props, samples/dotnet/BuildAllMauiApp/BuildAllMauiApp.csproj, source/GooglePlayServicesProject.cshtml
Context: https://github.com/xamarin/AndroidX/pull/875
With support for Classic Xamarin.Android [ended May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), we can start removing all the hacks needed to support both Classic and .NET for Android.
- No longer build EOL frameworks: `MonoAndroid12.0;net6.0-android;`
- No longer need to install classic XA
- No longer need to have classic XA or XF sample builds
- No longer need to use `Xamarin.Legacy.Sdk`
For this PR, we'll only build `net7.0-android`.  A future PR should enable `net8.0-android`.
=> Remove Classic support.

Directory.Build.props, build.cake
In https://github.com/xamarin/GooglePlayServicesComponents/pull/822 we started using a .NET 8 `generator` to build our `net7.0-android` packages.  Now that we have migrated to .NET 8 and can stay current with .NET releases this is no longer needed.
=> [build] Remove custom `generator` usage.

cgmanifest.json, docs/artifact-list-with-versions.md, samples/Directory.Build.targets, source/org.tensorflow/tensorflow-lite-support-api/Additions/Xamarin.TensorFlow.Lite.Support.Common.TensorProcessor.cs, source/org.tensorflow/tensorflow-lite-support-api/Additions/Xamarin.TensorFlow.Lite.Support.Image.ImageProcessor.cs, source/org.tensorflow/tensorflow-lite-support-api/Transforms/Metadata.xml
Yes. Methods surfaced and renamed
Fixes for issue #754 
Error:
```
./generated/org.tensorflow.tensorflow-lite-support-api/obj/Debug/net8.0-android/generated/src/Xamarin.TensorFlow.Lite.Support.Common.TensorProcessor.cs(163,20): error CS0102: The type 'TensorProcessor.Builder' already contains a definition for 'cb_build' [./generated/org.tensorflow.tensorflow-lite-support-api/org.tensorflow.tensorflow-lite-support-api.csproj::TargetFramework=net8.0-android]
./generated/org.tensorflow.tensorflow-lite-support-api/obj/Debug/net8.0-android/generated/src/Xamarin.TensorFlow.Lite.Support.Image.ImageProcessor.cs(196,20): error CS0102: The type 'ImageProcessor.Builder' already contains a definition for 'cb_build' [./generated/org.tensorflow.tensorflow-lite-support-api/org.tensorflow.tensorflow-lite- …
```
=> Manual updates 20240725 fix for issue 754

build/scripts/update-config.csx
We are hitting a corner case where our update script is not preserving the leading "1" that is generally prepended to a GPS NuGet version number.  Rewrite this part of the script to be more accurate.
=> [update-config.csx] Better detection of GPS packages prefixed with a "1".

config.json, source/com.google.android.play/app-update/Transforms/Metadata.xml
Fixes: https://github.com/xamarin/GooglePlayServicesComponents/issues/900
In April 2022, [Google deprecated](https://developer.android.com/reference/com/google/android/play/core/release-notes) the `com.google.android.play:core` package and split its functionality into four packages, including `com.google.android.play:app-update`.
We need to copy the fix in https://github.com/xamarin/GooglePlayServicesComponents/pull/709 to the new package in order for `StateUpdatedListener.onStateUpdate (InstallState)` to be implementable.
=> [app-update] Copy metadata from original "core" package.
