xamarin/GooglePlayServicesComponents

basement/buildtasks.tests/Basement.BuildTasks.Tests.csproj, basement/buildtasks.tests/BuildTaskTests.cs, basement/buildtasks.tests/Helpers/MSBuildExtensions.cs, basement/buildtasks.tests/Helpers/MSBuildTestLogger.cs, basement/buildtasks.tests/Helpers/TestsBase.cs, basement/buildtasks.tests/packages.config, basement/buildtasks/ProcessGoogleServicesJson.cs, basement/buildtasks/Xamarin.GooglePlayServices.Basement.targets
- Add support for incremental builds with Inputs and Outputs specified.  This way the task only runs when the input json file changes.
- Added written files to the FileWrites so they can be properly removed during a Clean.
- Added some tests.
=> Basement Build Task Improvements

azure-pipelines.yaml, config.json, source/com.google.android.gms/play-services-base/Transforms/Metadata.xml, source/com.google.android.gms/play-services-games/Transforms/Metadata.xml, source/com.google.firebase/firebase-common/Transforms/Metadata.xml, source/com.google.firebase/firebase-inappmessaging-display/Transforms/Metadata.Namespaces.xml, source/com.google.firebase/firebase-inappmessaging-display/Transforms/Metadata.xml, source/com.google.firebase/firebase-inappmessaging/Transforms/Metadata.Namespaces.xml, source/com.google.firebase/firebase-inappmessaging/Transforms/Metadata.xml
- com.google.android.gms.play-services-awareness (18.0.0 -> 18.0.1)
- [diff.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5643526/Xamarin.GooglePlayServices.Awareness.dll.diff.txt)
- com.google.android.gms.play-services-base (17.2.1 -> 17.4.0)
- [breaking.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5643540/Xamarin.GooglePlayServices.Base.dll.breaking.txt)
- [diff.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5643541/Xamarin.GooglePlayServices.Base.dll.diff.txt)
- com.google.android.gms.play-services-basement (17.2.1 -> 17.4.0)
- [breaking.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5643551/Xamarin.GooglePlayServices.Basement.dll.breaking.txt)
- …
=> GPS/FB August 2020 Updates

config.json, source/com.google.android.gms/play-services-ads-lite/Transforms/Metadata.xml, source/com.google.android.gms/play-services-cloud-messaging/Additions/Additions.cs, source/com.google.android.gms/play-services-cloud-messaging/Transforms/EnumFields.xml, source/com.google.android.gms/play-services-cloud-messaging/Transforms/EnumMethods.xml, source/com.google.android.gms/play-services-cloud-messaging/Transforms/Metadata.Namespaces.xml, source/com.google.android.gms/play-services-cloud-messaging/Transforms/Metadata.ParameterNames.xml, source/com.google.android.gms/play-services-cloud-messaging/Transforms/Metadata.xml, source/com.google.firebase/firebase-encoders/Additions/Additions.cs, source/com.google.firebase/firebase-encoders/Transforms/EnumFields.xml, source/com.google.firebase/firebase-encoders/Transforms/EnumMethods.xml, source/com.google.firebase/firebase-encoders/Transforms/Metadata.Namespaces.xml, source/com.google.firebase/firebase-encoders/Transforms/Metadata.ParameterNames.xml, source/com.google.firebase/firebase-encoders/Transforms/Metadata.xml, source/com.google.firebase/firebase-perf/Transforms/Metadata.xml
- com.google.android.gms.play-services-ads (19.3.0 -> 19.4.0)
- No public API changes
- com.google.android.gms.play-services-ads-base (19.3.0 -> 19.4.0)
- No public API changes
- com.google.android.gms.play-services-ads-lite (19.3.0 -> 19.4.0)
- [breaking.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5698829/Xamarin.GooglePlayServices.Ads.Lite.dll.breaking.txt)
- [diff.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5698830/Xamarin.GooglePlayServices.Ads.Lite.dll.diff.txt)
- com.google.android.gms.play-services-cloud-messaging (16.0.0)
- New binding
- com.google.android.gms.play-services-gass (19.3.0 -> 19.4.0)
- No public API changes
- com.google.android.gms.play-services-location (17.0.0 -> 17.1.0)
- …
=> GPS/FB September 2020 Updates

config.json, samples/com.google.firebase/firebase-config/FirebaseConfigQuickstart/MainActivity.cs, source/com.google.android.gms/play-services-base/Transforms/Metadata.xml, source/com.google.firebase/firebase-auth/Transforms/Metadata.xml
- com.google.android.gms.play-services-ads (19.4.0 -> 19.5.0)
- No public API changes
- com.google.android.gms.play-services-ads-base (19.4.0 -> 19.5.0)
- No public API changes
- com.google.android.gms.play-services-ads-lite (19.4.0 -> 19.5.0)
- [breaking.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5712192/Xamarin.GooglePlayServices.Ads.Lite.dll.breaking.txt)
- [diff.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5712193/Xamarin.GooglePlayServices.Ads.Lite.dll.diff.txt)
- com.google.android.gms.play-services-auth-api-phone (17.4.0 -> 17.5.0)
- [diff.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5712198/Xamarin.GooglePlayServices.Auth.Api.Phone.dll.diff.txt)
- com.google.android.gms.play-services-base (17.4.0 -> 17.5.0)
- …
=> GPS/FB October 2020 Updates

.github/workflows/new-releases-check.yml, build/scripts/update-config.csx
(Bringing this over from https://github.com/xamarin/AndroidX/pull/204)
Add a new GitHub Action that:
-  Checks for new stable releases in Google's Maven repository every Monday morning.
-  If new releases are found, updates the config.json with the new versions and opens a PR.
=> [Github Actions] Add action to check for stable releases each week.

samples/com.google.android.gms/play-services-maps/MapsSample/Properties/AssemblyInfo.cs
Fixes: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1220542/
=> Update samples to remove "secrets" such as API keys

build.cake, config.json, nuget-diff.cake, samples/Directory.Build.targets, source/com.google.android.gms/play-services-base/Transforms/Metadata.xml, source/com.google.android.gms/play-services-mlkit-image-labeling/Transforms/Metadata.Namespaces.xml, source/com.google.firebase/firebase-crashlytics/Transforms/Metadata.xml, source/com.google.firebase/firebase-firestore/Additions/Additions.cs, source/com.google.firebase/firebase-firestore/Transforms/Metadata.xml, source/com.google.mlkit/digital-ink-recognition/Transforms/Metadata.Namespaces.xml, source/com.google.mlkit/image-labeling-default-common/Transforms/Metadata.Namespaces.xml, source/com.google.mlkit/image-labeling-default-common/Transforms/Metadata.xml, source/com.google.mlkit/mediapipe-internal/Transforms/Metadata.Namespaces.xml, source/com.google.mlkit/mediapipe-internal/Transforms/Metadata.xml, source/com.google.mlkit/object-detection-custom/Transforms/Metadata.xml, source/com.google.mlkit/object-detection/Transforms/Metadata.xml, source/com.google.mlkit/pose-detection-accurate/Transforms/Metadata.Namespaces.xml, source/com.google.mlkit/pose-detection-accurate/Transforms/Metadata.xml, source/com.google.mlkit/pose-detection-common/Transforms/Metadata.Namespaces.xml, source/com.google.mlkit/pose-detection/Transforms/Metadata.Namespaces.xml
MLKit catching up + automatic weekly updates
- com.google.android.gms:play-services-base - 17.5.0 -> 17.6.0
- [diff.md.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/6004264/diff.md.txt)
- [breaking.md.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/6004263/breaking.md.txt)
- com.google.android.gms:play-services-basement - 17.5.0 -> 17.6.0
- [diff.md.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/6004270/diff.md.txt)
- [breaking.md.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/6004269/breaking.md.txt)
- com.google.android.gms:play-services-measurement - 18.0.1 -> 18.0.2
- No public API changes
- com.google.android.gms:play-services-measurement-api - 18.0.1 -> 18.0.2
- No public API changes
- …
=> updates-20210210 manual MLKit

source/GooglePlayServices-Firebase.Solution.proj, source/GooglePlayServicesProject.cshtml
* search improvements for nuget package
* short artifact id `group_id:artifact_id`
* long/versioned artifact id `group_id:artifact_id:version`
* parameter extraction improvements
* `JavaSourceJar`
* `JavaDocJar`
=> Improvements javadocjar javasourcejar

.github/workflows/new-releases-check.yml
=> change update check schedule every 2 weeks on monday

source/GooglePlayServicesProject.cshtml, source/com.google.android.gms/play-services-safetynet/Additions/Additions.cs
SafetyNet
No.
System.Json replaced with System.text.Json (JsonObject with JsonDocument)
=> System.Json replaced with System.text.Json (JsonObject with JsonDocument)

BUILDING.md, README.md
Update and optimize the README to be focused on targeting GPS/FB consumers:
- Add FAQs about versioning, time to bind new libraries, and pre-release policy.
- Move repo building instructions to a separate file.
=> Update and streamline the README.

azure-pipelines.yaml, build/scripts/update-config.csx, config.json, source/com.google.android.gms/play-services-oss-licenses/Transforms/Metadata.xml
Context: https://github.com/xamarin/AndroidX/pull/336
This currently does not have much effect on GPS like it does with AndroidX.
Dependencies added:
| Artifact  | Dependency |
| ------------- | ------------- |
com.google.android.gms.play-services-cast-framework|androidx.appcompat.appcompat
com.google.android.gms.play-services-oss-licenses|androidx.appcompat.appcompat
=> [build] Enable 'strictRuntimeDependencies'.

utilities.cake
No.
list of artifacts (with and without versions) task added to utilities
generates markdown tables:
|                                                                      |                                                                      |
|----------------------------------------------------------------------|----------------------------------------------------------------------|
|com.google.android.gms:play-services-ads                              |Xamarin.GooglePlayServices.Ads                                        |
|com.google.android.gms:play-services-ads-base                         |Xamarin.GooglePlayServices.Ads.Base                                   |
|com.google.android.gms:play-services-ads-identifier                   |Xamarin.GooglePlayServices.Ads.Identifier …
=> list of artifacts AKA bill of material BoM (with and without versions)

samples/com.google.firebase/firebase-ads/FirebaseAdmobQuickstart/google-services.json
Context: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1333190/
Update `google-services.json` to mirror the content in other Quickstart
sample projects.
=> [samples] Update Admob google-services.json

build/scripts/update-config.csx
Copy script from AndroidX:
https://github.com/xamarin/AndroidX/pull/367
=> [update-config.csx] Make changes to support template sets.

config.json, source/com.google.android.ump/user-messaging-platform/Transforms/Metadata.Namespaces.xml, source/com.google.android.ump/user-messaging-platform/Transforms/Metadata.xml, templates/user-messaging-platform/External-Dependency-Info.txt, templates/user-messaging-platform/LICENSE.md, templates/user-messaging-platform/Project.cshtml, templates/user-messaging-platform/cgmanifest.json, templates/user-messaging-platform/readme.md, utilities.cake
=> template set user-messaging-platform

config.json
=> nuget bumps 2021-12-11

utilities.cake
No.
Cleanup and consolitation of `utilities.cake`. Preparing for adding new "binding improvements" APIs for design and testing.
=> Minor improvements to utilities.cake (namespace checks, nuget structure …)

azure-pipelines.yaml, global.json, source/GooglePlayServicesProject.cshtml
=> CI updates - version bumps

build.cake
No.
bumped ANDROID_SDK_VERSION and AndroidSdkBuildTools
=> bumping ANDROID_SDK_VERSION and AndroidSdkBuildTools

config.json
No.
Bumping all nugets for publishing with trimmable support.
=> bump all for trimmable support

config.json, samples/Directory.Build.targets, source/com.google.mlkit/barcode-scanning/Additions/Barcode.cs, source/com.google.mlkit/barcode-scanning/Transforms/Metadata.xml, source/com.google.mlkit/digital-ink-recognition/Transforms/Metadata.xml, source/com.google.mlkit/image-labeling-custom-common/Additions/Additions.cs, source/com.google.mlkit/image-labeling-custom-common/Transforms/EnumFields.xml, source/com.google.mlkit/image-labeling-custom-common/Transforms/EnumMethods.xml, source/com.google.mlkit/image-labeling-custom-common/Transforms/Metadata.Namespaces.xml, source/com.google.mlkit/image-labeling-custom-common/Transforms/Metadata.ParameterNames.xml, source/com.google.mlkit/image-labeling-custom-common/Transforms/Metadata.xml, source/com.google.mlkit/linkfirebase/Transforms/Metadata.xml, source/com.google.mlkit/object-detection-custom/Transforms/Metadata.xml, source/com.google.mlkit/object-detection/Transforms/Metadata.xml, source/com.google.mlkit/translate/Transforms/Metadata.xml, source/com.google.mlkit/vision-common/Transforms/Metadata.xml, source/com.google.mlkit/vision-internal-vkp/Transforms/Metadata.xml
Possibly yes. New bindings.
bound
- com.google.android.gms:playservices-mlkit-face-detection - 16.2.0 -> 16.2.1
- com.google.mlkit:barcode-scanning - 16.2.0 -> 17.0.2
- com.google.mlkit:common - 18.0.0 -> 18.1.0
- com.google.mlkit:digitalink-recognition - 17.0.1 -> 18.0.0
- com.google.mlkit:face-detection - 16.1.2 -> 16.1.3
- com.google.mlkit:image-labeling - 17.0.5 -> 17.0.6
- com.google.mlkit:image-labeling-common - 17.1.0 -> 17.2.0
- com.google.mlkit:image-labeling-custom - 16.3.1 -> 17.0.0
- com.google.mlkit:image-labeling-default-common -  -> 16.0.2
- com.google.mlkit:language-id - 17.0.0 -> 17.0.1
- com.google.mlkit:linkfirebase - 16.1.1 -> 17.0.0
- com.google.mlkit:object-detection - 16.2.8 -> 17.0.0
- com.google.mlkit:object-detection-common - 17.2.0 -> 18.0.0
- …
=> Manual updates 20220516 MLKit

config.json, samples/Directory.Build.targets, source/io.grpc/grpc-core/Transforms/Metadata.xml, source/io.grpc/grpc-stub/Transforms/Metadata.xml
possibly.
grpc and dependecies bumps
=> manual updates 20260526 grpc 1.44.1 bumps (needed by Firebase)

config.json, samples/Directory.Build.targets, source/io.grpc/grpc-core/Transforms/Metadata.xml, source/io.grpc/grpc-stub/Transforms/Metadata.xml
could be.
grpc and dependencies bumps
=> manual updates 20260526 grpc 1.45.1 bumps (needed by Firebase)

config.json
Fixes: https://github.com/xamarin/GooglePlayServicesComponents/issues/648
=> Bump to 1.6.21.1 Xamarin.Kotlin packages

azure-pipelines.yaml, workloads.json
No.
1. created `workloads.json` with latest dotnet workloads
this approach needs discussion (different opiniones to use URL or file)
2. Updated CI config (`azure-pipelines.yml`) to use file
=> Using latest Workloads

.github/workflows/new-releases-check.yml, build/scripts/update-config.csx
Synchronizes `update-config.csx` script with AndroidX version.
This brings in:
- `published` functionality
- `sort` functionality
- `frozen` functionality
- Automatic updating for dependencies in AndroidX repository.
=> [update-config.csx] Synchronize script with AndroidX version.

cgmanifest.json, config.json, samples/Directory.Build.targets
Probably - version updates
- `com.google.mlkit:common` - 18.2.0 -> 18.3.0
- `com.google.mlkit:smart-reply` - 17.0.0 -> 17.0.1
- `com.google.mlkit:vision-interfaces` - 16.0.0 -> 16.1.0
=> Manual updates 20220821 MLKit

config.json, published-namespaces.txt, source/com.squareup.retrofit2/adapter-rxjava2/Transforms/Metadata.xml, source/com.squareup.retrofit2/converter-gson/Transforms/Metadata.xml, source/com.squareup.retrofit2/converter-scalars/Transforms/Metadata.xml, source/com.squareup.retrofit2/retrofit/Transforms/Metadata.xml, templates/squareup-retrofit2/External-Dependency-Info.txt, templates/squareup-retrofit2/License.md, templates/squareup-retrofit2/Project.cshtml
Import the remaining Retrofit packages from XamarinComponents into this repository so they can be supported.
=> Import Retrofit2 packages from XamarinComponents.

config.json, published-namespaces.txt, source/com.squareup.okhttp3/logging-interceptor/Transforms/Metadata.xml, templates/squareup-okhttp3/Project.cshtml
Move OkHttp3 related package `Square.OkHttp3.LoggingInterceptor` to this repository from XamarinComponents.
Package looks good:
=> Import Square.OkHttp3.LoggingInterceptor package from XamarinComponents.

utilities.cake
No.
licenses added for new packages w/o license info for component governance
=> component governance fixes - licenses added for new packages w/o license info

config.json, source/com.android.billingclient/billing/Transforms/Metadata.xml
Yes.  Surfaced API that was removed with `remove-node`.
Added metadata fix.
=> Fix for BillingClient issue 740

Directory.Build.props, utilities.cake, workloads.json
Context: https://github.com/xamarin/AndroidX/pull/809
=> Building with net7.0-android TFM

config.json
Fixes: https://github.com/xamarin/GooglePlayServicesComponents/issues/832
=> Bump `Xamarin.Google.Android.Recaptcha` to `18.4.0`.

cgmanifest.json, config.json, docs/artifact-list-with-versions.md, samples/Directory.Build.targets, source/GooglePlayServicesDirectoryBuildRsp.cshtml
No.
In order to get more information and isolated information the template to generate per project (`csproj`) was added.
Template generates `Directory.Build.rsp` with
- binlogger
- fileloggers
with diagnostic output.
=> Manual updates 20240208 improvements - template for `Directory.Build.rsp`

Directory.Build.props, azure-pipelines.yaml, build.cake, global.json, workloads.json
No.
Tooling versions bumped only.
=> Manual updates 20240410 - tooling version bumps

templates/aopalliance/Project.cshtml
No.
`public` license for AOPAlliance does not exists on https://spdx.org/licenses/
=> [DO NOT MERGE][PUBLISH FROM BRANCH] Fix for public license

.editorconfig
=> Manual updates 20240625 - .editorconfig
